# Generated by Django 6.0.3 on 2026-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
